eshop/Models/SystemUser.cs
using System;
using System.Collections.Generic;

namespace eshop.Models
{
    public partial class SystemUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public string Status { get; set; }
        public string Role { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string ProfilePicture { get; set; }
    }
}

eshop/Controllers/SystemCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eshop.Models;

namespace eshop.Controllers
{
    public class SystemCategoriesController : Controller
    {
        private readonly eshopContext _context;

        public SystemCategoriesController(eshopContext context)
        {
            _context = context;
        }

        // GET: SystemCategories
        public async Task<IActionResult> Index()
        {
            return View(await _context.SystemCategory.ToListAsync());
        }

        // GET: SystemCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemCategory = await _context.SystemCategory
                .FirstOrDefaultAsync(m => m.Id == id);
            if (systemCategory == null)
            {
                return NotFound();
            }

            return View(systemCategory);
        }

        // GET: SystemCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SystemCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Picture,Status,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] SystemCategory systemCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(systemCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(systemCategory);
        }

        // GET: SystemCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemCategory = await _context.SystemCategory.FindAsync(id);
            if (systemCategory == null)
            {
                return NotFound();
            }
            return View(systemCategory);
        }

        // POST: SystemCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Picture,Status,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] SystemCategory systemCategory)
        {
            if (id != systemCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(systemCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SystemCategoryExists(systemCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(systemCategory);
        }

        // GET: SystemCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemCategory = await _context.SystemCategory
                .FirstOrDefaultAsync(m => m.Id == id);
            if (systemCategory == null)
            {
                return NotFound();
            }

            return View(systemCategory);
        }

        // POST: SystemCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var systemCategory = await _context.SystemCategory.FindAsync(id);
            _context.SystemCategory.Remove(systemCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SystemCategoryExists(int id)
        {
            return _context.SystemCategory.Any(e => e.Id == id);
        }
    }
}

eshop/Controllers/SystemItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eshop.Models;

namespace eshop.Controllers
{
    public class SystemItemsController : Controller
    {
        private readonly eshopContext _context;

        public SystemItemsController(eshopContext context)
        {
            _context = context;
        }

        // GET: SystemItems
        public async Task<IActionResult> Index()
        {
            return View(await _context.SystemItem.ToListAsync());
        }

        // GET: SystemItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemItem = await _context.SystemItem
                .FirstOrDefaultAsync(m => m.Id == id);
            if (systemItem == null)
            {
                return NotFound();
            }

            return View(systemItem);
        }

        // GET: SystemItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SystemItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Quantity,CostPice,SalePrice,MainImage,ItemCode,Status,ItemCategory,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] SystemItem systemItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(systemItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(systemItem);
        }

        // GET: SystemItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemItem = await _context.SystemItem.FindAsync(id);
            if (systemItem == null)
            {
                return NotFound();
            }
            return View(systemItem);
        }

        // POST: SystemItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Quantity,CostPice,SalePrice,MainImage,ItemCode,Status,ItemCategory,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] SystemItem systemItem)
        {
            if (id != systemItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(systemItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SystemItemExists(systemItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(systemItem);
        }

        // GET: SystemItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemItem = await _context.SystemItem
                .FirstOrDefaultAsync(m => m.Id == id);
            if (systemItem == null)
            {
                return NotFound();
            }

            return View(systemItem);
        }

        // POST: SystemItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var systemItem = await _context.SystemItem.FindAsync(id);
            _context.SystemItem.Remove(systemItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SystemItemExists(int id)
        {
            return _context.SystemItem.Any(e => e.Id == id);
        }
    }
}

eshop/Controllers/SystemUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using eshop.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace eshop.Controllers
{
    public class SystemUsersController : Controller
    {
        private readonly eshopContext _context;

        private readonly IHostingEnvironment _env;

        public SystemUsersController(eshopContext context, IHostingEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: SystemUsers
        public async Task<IActionResult> Index()
        {
            if (AuthenticateUser())
            {
                return View(await _context.SystemUser.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login");
            }

        }

        
        




        // GET: SystemUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemUser = await _context.SystemUser
                .FirstOrDefaultAsync(m => m.Id == id);
            if (systemUser == null)
            {
                return NotFound();
            }

            return View(systemUser);
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(SystemUser U)
        {
            SystemUser LoggedInUser = _context.SystemUser.Where(abc => abc.Username == U.Username && abc.Password == U.Password).FirstOrDefault();

            if (LoggedInUser == null)
            {
                ViewBag.Message = "Invalid Username or Password";
                return View();
            }


            ////Maintain User Server Side Session
            HttpContext.Session.SetString("Username", LoggedInUser.Username);
            HttpContext.Session.SetString("UserRole", LoggedInUser.Role);
            HttpContext.Session.SetString("UserDisplayName", LoggedInUser.DisplayName);
            if (LoggedInUser.Role == "Admin")
            {
                return RedirectToAction("AdminDashboard");
            }
            else
            {
                return RedirectToAction("UserDashboard");
            }
        }
          


            public IActionResult Logout()
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Login");
            }



            public bool AuthenticateUser()
            {


                return true;
            }
        


        // GET: SystemUsers/Create
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult AdminDashboard()
        {
            return View();
        }
        public IActionResult UserDashboard()
        {
            return View();
        }

        // POST: SystemUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Username,Password,DisplayName,Status,Role,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,ProfilePicture")] SystemUser systemUser, IFormFile ProfilePicture)
        {
            if (ModelState.IsValid)
            {
                if (ProfilePicture != null)
                {
                    string FileName = Guid.NewGuid().ToString() + Path.GetExtension(ProfilePicture.FileName);
                    string FilePath = _env.WebRootPath + "/SystemData/ProfilePictures/";
                    FileStream FS = new FileStream(FilePath + FileName, FileMode.Create);
                    ProfilePicture.CopyTo(FS);
                    FS.Close();
                    systemUser.ProfilePicture = "/SystemData/ProfilePictures/" + FileName;
                }

                systemUser.Status = "Active";
                systemUser.Role = "staff";
                systemUser.CreatedDate = DateTime.Now;
                systemUser.CreatedBy = "Self";
                _context.Add(systemUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(systemUser);
        }

        // GET: SystemUsers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemUser = await _context.SystemUser.FindAsync(id);
            if (systemUser == null)
            {
                return NotFound();
            }
            return View(systemUser);
        }

        // POST: SystemUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Username,Password,DisplayName,Status,Role,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy,ProfilePicture")] SystemUser systemUser)

        {
            if (id != systemUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(systemUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SystemUserExists(systemUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(systemUser);
        }

        // GET: SystemUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var systemUser = await _context.SystemUser
                .FirstOrDefaultAsync(m => m.Id == id);
            if (systemUser == null)
            {
                return NotFound();
            }

            return View(systemUser);
        }

        // POST: SystemUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var systemUser = await _context.SystemUser.FindAsync(id);
            _context.SystemUser.Remove(systemUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SystemUserExists(int id)
        {
            return _context.SystemUser.Any(e => e.Id == id);
        }
    }
}

eshop/Views/SystemUsers/AdminDashboard.cshtml
@model IEnumerable<eshop.Models.SystemUser>
@{
    ViewData["Title"] = "AdminDashboard";
}

<h2>AdminDashboard</h2>


<h1 class="text-center alert alert-success">Admin Dashboard</h1>

<p>
    <a asp-action="Index">View All Users</a>
</p>


<li><a asp-area="" asp-controller="SystemCategories" asp-action="create">Add new Category</a></li>
<li><a asp-area="" asp-controller="SystemCategories" asp-action="index">View all categories</a></li>
<li><a asp-area="" asp-controller="SystemItems" asp-action="index">View all Items</a></li>

<ul class="nav navbar-nav">
    <li>
    <a asp-area="" asp-controller="SystemUsers" asp-action="Login">Logout</a></li>

</ul>

eshop/Views/SystemUsers/Create.cshtml
@model eshop.Models.SystemUser

@{
    ViewData["Title"] = "Register User";
}

<h2>Please fill the detail to register</h2>

<h4>SystemUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayName" class="control-label"></label>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePicture" class="form-control" type="file"/>
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

eshop/Views/SystemUsers/Delete.cshtml
@model eshop.Models.SystemUser

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SystemUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

eshop/Views/SystemUsers/Details.cshtml
@model eshop.Models.SystemUser

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>SystemUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

eshop/Views/SystemUsers/Edit.cshtml
@model eshop.Models.SystemUser

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>SystemUser</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayName" class="control-label"></label>
                <input asp-for="DisplayName" class="form-control" />
                <span asp-validation-for="DisplayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <input asp-for="Role" class="form-control" />
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedDate" class="control-label"></label>
                <input asp-for="ModifiedDate" class="form-control" />
                <span asp-validation-for="ModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePicture" class="control-label"></label>
                <input asp-for="ProfilePicture" class="form-control" type="file"/>
                <span asp-validation-for="ProfilePicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

eshop/Views/SystemUsers/Login.cshtml
@model eshop.Models.SystemUser
@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>
<h1>Please enter Username and Password to Proceed!</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type="password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

eshop/Views/SystemUsers/UserDashboard.cshtml
@{
    ViewData["Title"] = "UserDashboard";
}

<h1 class="text-center alert alert-success">User Dashboard</h1>

<p>
    <a asp-action="Index">View All Users</a>
</p>


<li><a asp-area="" asp-controller="SystemCategories" asp-action="create">Add new Category</a></li>
<li><a asp-area="" asp-controller="SystemCategories" asp-action="index">View all categories</a></li>
<li><a asp-area="" asp-controller="SystemItems" asp-action="index">View all Items</a></li>
<ul class="nav navbar-nav">
    <li>
        <a asp-area="" asp-controller="SystemUsers" asp-action="Login">Logout</a>
    </li>

</ul>